btsync:
  image: ckulka/rpi-btsync
  ports:
    - "5555:5555"
    - "8888:8888"

backup:
  image: ckulka/rpi-awscli
  volumes_from:
    - btsync
  environment:
    - AWS_ACCESS_KEY_ID=my-access-key-id
    - AWS_SECRET_ACCESS_KEY=my-access-key-secret
    - AWS_DEFAULT_REGION=eu-central-1
    - BACKUP_LOCAL=/var/www/Specific
    - BACKUP_S3=s3://my-backup-bucket/btsync
  command: "sh /opt/aws-s3-sync-restore.sh"
